-- SamMart V1 — normalized marketplace schema
-- Rules: DECIMAL money, UNIQUE email, FK indexes, created_at on every table,
--        CHECK constraints, no FLOAT currency.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)  NOT NULL,
    email           VARCHAR(255)  NOT NULL,
    password_hash   VARCHAR(60)   NOT NULL,
    role            VARCHAR(10)   NOT NULL,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('BUYER', 'SELLER', 'ADMIN')),
    CONSTRAINT ck_users_name CHECK (LENGTH(TRIM(name)) >= 2)
);

CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_created_at ON users (created_at);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80)  NOT NULL,
    slug        VARCHAR(80)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    BIGINT         NOT NULL,
    category_id  BIGINT         NOT NULL,
    name         VARCHAR(150)   NOT NULL,
    description  VARCHAR(2000)  NOT NULL,
    price        DECIMAL(10, 2) NOT NULL,
    stock_qty    INT            NOT NULL,
    image_url    VARCHAR(500),
    is_active    BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_seller   FOREIGN KEY (seller_id)   REFERENCES users (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_products_price    CHECK (price >= 0.01),
    CONSTRAINT ck_products_stock    CHECK (stock_qty >= 0),
    CONSTRAINT ck_products_name     CHECK (LENGTH(TRIM(name)) >= 2)
);

CREATE INDEX idx_products_seller_id   ON products (seller_id);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_is_active   ON products (is_active);
CREATE INDEX idx_products_name        ON products (name);

CREATE TABLE cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT    NOT NULL,
    product_id  BIGINT    NOT NULL,
    quantity    INT       NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_user    FOREIGN KEY (user_id)    REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_cart_user_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_cart_qty CHECK (quantity > 0)
);

CREATE INDEX idx_cart_user_id    ON cart_items (user_id);
CREATE INDEX idx_cart_product_id ON cart_items (product_id);

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id       BIGINT         NOT NULL,
    status         VARCHAR(16)    NOT NULL DEFAULT 'PENDING',
    total_amount   DECIMAL(10, 2) NOT NULL,
    payment_ref    VARCHAR(64),
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_buyer   FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT ck_orders_status  CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_total   CHECK (total_amount >= 0.00)
);

CREATE INDEX idx_orders_buyer_id   ON orders (buyer_id);
CREATE INDEX idx_orders_status     ON orders (status);
CREATE INDEX idx_orders_created_at ON orders (created_at);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT         NOT NULL,
    product_id  BIGINT         NOT NULL,
    quantity    INT            NOT NULL,
    unit_price  DECIMAL(10, 2) NOT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_oi_order   FOREIGN KEY (order_id)   REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_oi_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_oi_qty   CHECK (quantity > 0),
    CONSTRAINT ck_oi_price CHECK (unit_price >= 0.01)
);

CREATE INDEX idx_oi_order_id   ON order_items (order_id);
CREATE INDEX idx_oi_product_id ON order_items (product_id);

CREATE TABLE payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT         NOT NULL,
    amount           DECIMAL(10, 2) NOT NULL,
    method           VARCHAR(16)    NOT NULL DEFAULT 'MOCK',
    status           VARCHAR(16)    NOT NULL,
    transaction_ref  VARCHAR(64)    NOT NULL,
    created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pay_order     FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT uq_pay_order     UNIQUE (order_id),
    CONSTRAINT uq_pay_txn       UNIQUE (transaction_ref),
    CONSTRAINT ck_pay_status    CHECK (status IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_pay_amount    CHECK (amount >= 0.01)
);

CREATE INDEX idx_payments_order_id ON payments (order_id);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT        NOT NULL,
    user_id     BIGINT        NOT NULL,
    order_id    BIGINT        NOT NULL,
    rating      INT           NOT NULL,
    comment     VARCHAR(1000) NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rev_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_rev_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_rev_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT uq_rev_user_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_rev_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_rev_comment CHECK (LENGTH(TRIM(comment)) >= 3)
);

CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_reviews_user_id    ON reviews (user_id);
CREATE INDEX idx_reviews_order_id   ON reviews (order_id);

CREATE TABLE inventory_movements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL,
    delta       INT         NOT NULL,
    reason      VARCHAR(16) NOT NULL,
    order_id    BIGINT,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inv_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT ck_inv_reason  CHECK (reason IN ('SALE', 'RESTOCK', 'ADJUST', 'CANCEL'))
);

CREATE INDEX idx_inv_product_id ON inventory_movements (product_id);
CREATE INDEX idx_inv_order_id   ON inventory_movements (order_id);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT,
    action       VARCHAR(40)   NOT NULL,
    entity_type  VARCHAR(40)   NOT NULL,
    entity_id    BIGINT,
    details      VARCHAR(500),
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);

CREATE INDEX idx_audit_actor_id   ON audit_logs (actor_id);
CREATE INDEX idx_audit_created_at ON audit_logs (created_at);

CREATE VIEW v_product_rating AS
SELECT p.id AS product_id,
       COALESCE(AVG(CAST(r.rating AS DECIMAL(10, 2))), 0) AS avg_rating,
       COUNT(r.id) AS review_count
FROM products p
LEFT JOIN reviews r ON r.product_id = p.id
GROUP BY p.id;

CREATE VIEW v_seller_sales AS
SELECT p.seller_id,
       COUNT(DISTINCT oi.order_id) AS order_count,
       COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS revenue
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.id
LEFT JOIN orders o ON o.id = oi.order_id AND o.status <> 'CANCELLED'
GROUP BY p.seller_id;
